apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spring-petclinic
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: container
          resources:
            limits:
              memory: 512Mi
          image: >-
            image-registry.openshift-image-registry.svc:5000/openshift/mariadb:latest
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: database-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: database-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: database-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: database-name
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql/data             
      volumes:
        - name: 'mariadb-data'
          persistentVolumeClaim:
            claimName: 'mariadb' 
