kind: Secret
apiVersion: v1
metadata:
  name: mariadb
  namespace: spring-petclinic
  labels:
    app.openshift.io/runtime: mariadb
    app: mariadb
data:
  database-name: cGV0Y2xpbmlj
  database-password: UGxlYXNlQ2hhbmdlVGhpcyEhIQo=
  database-root-password: UGxlYXNlQ2hhbmdlVGhpcyEhIQo=
  database-user: cGV0Y2xpbmlj
type: Opaque
